### ISSUE TITLE
Generalized GraphQL API for Avinya Foundation data

### ISSUE THREAD

**Issue by rukmal** [Avinya-Foundation/global-data#10]
This ticket covers the functionality of the generalized API for foundation data. To simplify development, a complete vertical slice (testing, integration, deployment, etc.) will be implemented with the Geo data tranche, followed by a sequential addition of tranches of the generalized data model.

- [x] #11
- [x] #19
- [x] #20
- [x] #21
- [x] WorkExperience tranche
- [x] EducationExperience tranche
- [ ] Evaluation tranche

**Comment by samisa-abeysinghe** [comment]
All entities and their query logic are in the code repo now
